resource "local_sensitive_file" "games" {
  filename     = "/root/favorite-games"
  content  = "FIFA 21" #This content won't be displayed in the execution plan
}

resource "local_file" "welcome" {
    filename = "/root/message.txt"
    content = "Welcome to Kodekloud."
}

output "welcome_message" {
	
	value = local_file.welcome.content
	description = "Record the value of pet ID generated by the random_pet resource"
}

