resource "local_sensitive_file" "games" {
  filename     = "/root/favorite-games"
  content  = "FIFA 21" #This content won't be displayed in the execution plan
}

resource "local_file" "welcome" {
    filename = "/root/message.txt"
    content = "Welcome to Kodekloud."
}

output "welcome_message" {
	
	value = local_file.welcome.content
	description = "Record the value of pet ID generated by the random_pet resource"
}

resource "random_string" "string" {
    length = var.length
    keepers = {
        length = var.length
    }  
    lifecycle {
      create_before_destroy = true
    }
}

resource "random_pet" "super_pet" {
    length = var.length
    prefix = var.prefix
   
   lifecycle {
     prevent_destroy = true
   }
}

output "os-version" {
  value = data.local_file.os.content
}
data "local_file" "os" {
  filename = "/etc/os-release"
}

resource "local_sensitive_file" "name" {
    filename = var.users[count.index]
    content = var.content
    count = 3
}

resource "local_sensitive_file" "name" {
    filename = each.value
    content = var.content
    for_each = toset(var.users)
}

terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "1.2.2"
    }
    google = {
      source  = "hashicorp/google"
      version = "> 3.45.0, !=3.46.0, < 3.48.0"
    }
    k8s = {
      source  = "hashicorp/kubernetes"
      version = "> 1.12.0, != 1.13.1, < 1.13.3 "
    }

    helm = {
      source  = "hashicorp/helm"
      version = "~> 1.2.0"
    }
  }
}
