resource "local_sensitive_file" "games" {
  filename     = "/root/favorite-games"
  content  = "FIFA 21" #This content won't be displayed in the execution plan
}

resource "local_file" "welcome" {
    filename = "/root/message.txt"
    content = "Welcome to Kodekloud."
}

output "welcome_message" {
	
	value = local_file.welcome.content
	description = "Record the value of pet ID generated by the random_pet resource"
}

resource "random_string" "string" {
    length = var.length
    keepers = {
        length = var.length
    }  
    lifecycle {
      create_before_destroy = true
    }
}

resource "random_pet" "super_pet" {
    length = var.length
    prefix = var.prefix
   
   lifecycle {
     prevent_destroy = true
   }
}

output "os-version" {
  value = data.local_file.os.content
}
data "local_file" "os" {
  filename = "/etc/os-release"
}
